export const USER_LOGIN = "USER_LOGIN"
export const USER_ADD_VERYTIFICATION_ID="USER_ADD_VERYTIFICATION_ID"

export const USER_GET_CONTACTS_TO_STATE = "GET_CONTACTS_TO_STATE"

export const USER_SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED"

export const USER_SET_IS_ONLINE = "USER_SET_IS_ONLINE"

export const USER_CHECK_BY_TOKEN="USER_CHECK_BY_TOKEN"
export const USER_LOGOUT=" USER_LOGOUT"

export const USER_SELECT_CHAT="USER_SELECT_CHAT"


export const USER_LOADING_START = "USER_LOADING_START"
export const USER_LOADING_END = "USER_LOADING_END"
export const USER_LOADING_ERROR = "USER_LOADING_ERROR"
export const USER_AUTH_ERROR = "USER_LOADING_ERROR"

